---
# Build opencv on ...
- hosts: localhost
  become: yes
  become_method: sudo
  connection: local
  gather_facts: no

  tasks:
   - name: Install pkgs
     apt: name= "{{ item }}" state=present
     with_items:
      - libjpeg-dev
      - libpng-dev
      - libtiff-dev    
     tags: pict

   - name: Install pkgs
     apt: name= "{{ item }}" state=present
     with_items:
      - libavcodec-dev
      - libavformat-dev
      - libswscale-dev
      - libv4l-dev
     tags: view

   - name: Install pkgs
     apt: name= "{{ item }}" state=present
     with_items:
      - libxvidcore-dev
      - libx264-dev
     tags: sys


